# Generated by Django 5.2.7 on 2025-10-30 18:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the camping plot', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the plot')),
                ('size', models.DecimalField(decimal_places=2, help_text='Size in square meters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of people', validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, help_text='Image of the camping plot', null=True, upload_to='lands/')),
                ('amenities', models.TextField(blank=True, help_text='Available amenities (e.g., water, electricity, fire pit)')),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Land Plot',
                'verbose_name_plural': 'Land Plots',
                'ordering': ['name'],
            },
        ),
    ]
