# Generated by Django 5.2.7 on 2025-10-30 19:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Price per night for this specific plot', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
